name: Monthly Dashboard Update
on:
  schedule:
    # Runs at 00:00 UTC on the 1st of every month
    - cron: '0 0 1 * *'
  workflow_dispatch: # Allows manual triggering
  push:
    branches: [ main ] # Also run on push for testing

jobs:
  update-dashboard:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history to avoid issues
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt --break-system-packages
        
    - name: Debug environment
      run: |
        echo "Current directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        echo "Python packages installed:"
        pip list | grep -E "(pandas|requests|weo)"
        
    - name: Run data processing script
      run: |
        echo "Starting script execution..."
        python -u script.py
        echo "Script completed with exit code: $?"
        
    - name: Check if files were updated
      run: |
        echo "Files after script:"
        ls -la *.html *.csv 2>/dev/null || echo "No html/csv files found"
        echo "Git status:"
        git status
        
    - name: Configure Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
    - name: Commit and push if changes
      run: |
        git add index.html weo.csv
        if git diff --staged --quiet; then
          echo "No changes to commit - files are up to date"
          exit 0
        fi
        
        # Pull latest changes to avoid conflicts
        git pull origin main --rebase
        
        # Commit the changes
        git commit -m "Update dashboard data - $(date +'%Y-%m-%d %H:%M:%S UTC')"
        
        # Push with retry logic
        for i in {1..3}; do
          if git push origin main; then
            echo "Successfully pushed changes"
            break
          else
            echo "Push failed, attempt $i/3. Pulling latest changes..."
            git pull origin main --rebase
            if [ $i -eq 3 ]; then
              echo "Failed to push after 3 attempts"
              exit 1
            fi
            sleep 5
          fi
        done
